#ifndef __binning_shader__H__
#define __binning_shader__H__

#include <stddef.h>

static const size_t binning_shader_size = 27816;
static const char binning_shader[] =
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Structures\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct draw_command \n"
    "{\n"
    "    data_index : u32,\n"
    "    flags      : u32 // extra (8) | clip_index (8) | fillmode (8) | type (8)\n"
    "};\n"
    "\n"
    "struct tile_node\n"
    "{\n"
    "    next          : u32,\n"
    "    command_index : u32 // command index + command type\n"
    "};\n"
    "\n"
    "struct counters\n"
    "{\n"
    "    num_nodes : atomic<u32>,\n"
    "    num_tiles : atomic<u32>\n"
    "};\n"
    "\n"
    "struct draw_args \n"
    "{\n"
    "    clear_color: vec4<f32>,\n"
    "    screen_div: vec2<f32>,\n"
    "    num_commands: u32,\n"
    "    num_tile_width: u32,\n"
    "    num_tile_height: u32,\n"
    "    max_nodes: u32,\n"
    "    aa_width: f32,\n"
    "    options: u32,\n"
    "};\n"
    "\n"
    "struct glyph\n"
    "{\n"
    "    uv_topleft : vec2<f32>,\n"
    "    uv_bottomright : vec2<f32>,\n"
    "    width : f32,\n"
    "    height : f32\n"
    "};\n"
    "\n"
    "struct clip_rect\n"
    "{\n"
    "    min_x : f32,\n"
    "    min_y : f32,\n"
    "    max_x : f32,\n"
    "    max_y : f32\n"
    "};\n"
    "\n"
    "struct aabb\n"
    "{\n"
    "    min : vec2<f32>,\n"
    "    max : vec2<f32>\n"
    "};\n"
    "\n"
    "struct obb\n"
    "{\n"
    "    axis_i : vec2<f32>,\n"
    "    axis_j : vec2<f32>,\n"
    "    center : vec2<f32>,\n"
    "    extents : vec2<f32>\n"
    "}\n"
    "\n"
    "struct indirect_params \n"
    "{\n"
    "    vertex_count: u32,\n"
    "    instance_count: u32,\n"
    "    first_vertex: u32,\n"
    "    first_instance: u32\n"
    "};\n"
    "\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn get_extra(cmd: draw_command) -> u32  {return cmd.flags & 0xFFu;}\n"
    "fn get_clip(cmd: draw_command) -> u32 {return (cmd.flags >> 8u) & 0xFFu;}\n"
    "fn get_fillmode(cmd: draw_command) -> u32 {return (cmd.flags >> 16u) & 0xFFu;}\n"
    "fn get_type(cmd: draw_command) -> u32 {return (cmd.flags >> 24u) & 0xFFu;}\n"
    "fn get_command_index(n : tile_node) -> u32 {return n.command_index & 0xFFFFu;}\n"
    "fn get_command_type(n : tile_node) -> u32 {return (n.command_index >> 16u) & 0xFFu;}\n"
    "\n"
    "\n"
    "/*\n"
    "\n"
    "//-----------------------------------------------------------------------------\n"
    "// based on https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-23-high-speed-screen-particles\n"
    "// we also use a specific blend equation\n"
    "half4 accumulate_color(half4 color, half4 backbuffer)\n"
    "{\n"
    "    half4 output;\n"
    "    output.rgb = (color.rgb * color.a) + (backbuffer.rgb * (1.f - color.a));\n"
    "    output.a = backbuffer.a * (1.f - color.a);\n"
    "    return output;\n"
    "}\n"
    "\n"
    "*/\n"
    "\n"
    "fn accumulate_color(color: vec4<f32>, backbuffer: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    let rgb = mix(backbuffer.rgb, color.rgb, color.a);\n"
    "    return vec4<f32>(rgb, 1.0);\n"
    "}\n"
    "\n"
    "fn linear_to_srgb_channel(c: f32) -> f32 \n"
    "{\n"
    "    if (c <= 0.0031308) \n"
    "    {\n"
    "        return c * 12.92;\n"
    "    } else \n"
    "    {\n"
    "        return 1.055 * pow(c, 1.0 / 2.4) - 0.055;\n"
    "    }\n"
    "}\n"
    "\n"
    "fn linear_to_srgb(linear_color: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    return vec4<f32>(\n"
    "        linear_to_srgb_channel(linear_color.r),\n"
    "        linear_to_srgb_channel(linear_color.g),\n"
    "        linear_to_srgb_channel(linear_color.b),\n"
    "        linear_color.a\n"
    "    );\n"
    "}\n"
    "\n"
    "fn srgb_to_linear(srgb: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    let rgb = srgb.rgb;\n"
    "    let linear_rgb = select(\n"
    "        pow((rgb + 0.055) / 1.055, vec3<f32>(2.4)),\n"
    "        rgb / 12.92,\n"
    "        rgb <= vec3<f32>(0.04045)\n"
    "    );\n"
    "    return vec4<f32>(linear_rgb, srgb.a);\n"
    "}\n"
    "\n"
    "fn saturate(x: f32) -> f32 \n"
    "{\n"
    "    return clamp(x, 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn linearstep(edge0: f32, edge1: f32, x: f32) -> f32 \n"
    "{\n"
    "    return clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn skew(v: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    return vec2<f32>(-v.y, v.x);\n"
    "}\n"
    "\n"
    "fn distance_squared(a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    let d = a - b;\n"
    "    return dot(d, d);\n"
    "}\n"
    "\n"
    "fn length_squared(v: vec2<f32>) -> f32 \n"
    "{\n"
    "    return dot(v, v);\n"
    "}\n"
    "\n"
    "fn square(x: f32) -> f32 \n"
    "{\n"
    "    return x * x;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Constants\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "const TILE_SIZE: f32 = 16.0;\n"
    "const PRIMITIVE_CHAR: u32 = 0u;\n"
    "const PRIMITIVE_AABOX: u32 = 1u;\n"
    "const PRIMITIVE_ORIENTED_BOX: u32 = 2u;\n"
    "const PRIMITIVE_DISC: u32 = 3u;\n"
    "const PRIMITIVE_TRIANGLE: u32 = 4u;\n"
    "const PRIMITIVE_ELLIPSE: u32 = 5u;\n"
    "const PRIMITIVE_PIE: u32 = 6u;\n"
    "const PRIMITIVE_ARC: u32 = 7u;\n"
    "const PRIMITIVE_BLURRED_BOX: u32 = 8u;\n"
    "const PRIMITIVE_QUAD: u32 = 9u;\n"
    "const PRIMITIVE_ORIENTED_QUAD: u32 = 10u;\n"
    "const BEGIN_GROUP: u32 = 32u;\n"
    "const END_GROUP: u32 = 33u;\n"
    "const INVALID_INDEX:u32 = 0xFFFFFFFFu;\n"
    "const OP_UNION:u32 = 0u;\n"
    "const OP_SUBTRACTION:u32 = 1u;\n"
    "const OP_INTERSECTION:u32 = 2u;\n"
    "const FILL_SOLID:u32 = 0u;\n"
    "const FILL_OUTLINE:u32 = 1u;\n"
    "const FILL_HOLLOW:u32 = 2u;\n"
    "const FILL_GRADIENT:u32 = 3u;\n"
    "const OPTION_SRGB_BACKBUFFER:u32 = (1u<<0);\n"
    "const OPTION_DEBUG_BINNING:u32 = (1u<<1);\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Bindgroups\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "// group 0 : static or updated on gpu\n"
    "@group(0) @binding(0)\n"
    "var<storage, read_write> g_tile_nodes : array<tile_node>;\n"
    "\n"
    "@group(0) @binding(1)\n"
    "var<storage, read_write> g_tile_indices : array<u32>;\n"
    "\n"
    "@group(0) @binding(2)\n"
    "var<storage, read_write> g_counters : counters;\n"
    "\n"
    "@group(0) @binding(3)\n"
    "var<storage, read_write> g_tile_heads : array<u32>;\n"
    "\n"
    "@group(0) @binding(4)\n"
    "var<storage, read_write> g_indirect_draw : indirect_params;\n"
    "\n"
    "// group 1 : updated each frame\n"
    "@group(1) @binding(0)\n"
    "var<storage, read> g_draw_args: draw_args;\n"
    "\n"
    "@group(1) @binding(1)\n"
    "var<storage, read> g_commands : array<draw_command>;\n"
    "\n"
    "@group(1) @binding(2)\n"
    "var<storage, read> g_quantized_aabb : array<u32>;\n"
    "\n"
    "@group(1) @binding(3)\n"
    "var<storage, read> g_draw_data: array<f32>;\n"
    "\n"
    "@group(1) @binding(4)\n"
    "var<storage, read> g_clips: array<clip_rect>;\n"
    "\n"
    "@group(1) @binding(5)\n"
    "var<storage, read> g_colors: array<u32>;\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Helpers\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn aabb_grow(box: aabb, amount: vec2<f32>) -> aabb \n"
    "{\n"
    "    return aabb(box.min - amount, box.max + amount);\n"
    "}\n"
    "\n"
    "fn aabb_get_extents(box: aabb) -> vec2<f32> {return box.max - box.min;}\n"
    "\n"
    "fn compute_obb(p0: vec2<f32>, p1: vec2<f32>, width: f32) -> obb \n"
    "{\n"
    "    var result: obb;\n"
    "\n"
    "    result.center = (p0 + p1) * 0.5;\n"
    "    result.axis_j = p1 - result.center;\n"
    "    result.extents.y = length(result.axis_j);\n"
    "    result.axis_j = result.axis_j / result.extents.y;\n"
    "    result.axis_i = skew(result.axis_j);\n"
    "    result.extents.x = width * 0.5;\n"
    "\n"
    "    return result;\n"
    "}\n"
    "\n"
    "fn obb_transform(obox: obb, point: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    let p = point - obox.center;\n"
    "    return vec2<f32>(\n"
    "        abs(dot(obox.axis_i, p)),\n"
    "        abs(dot(obox.axis_j, p))\n"
    "    );\n"
    "}\n"
    "\n"
    "fn edge_distance(p: vec2<f32>, a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    return (b.y - a.y) * (p.x - a.x) - (b.x - a.x) * (p.y - a.y);\n"
    "}\n"
    "\n"
    "fn edge_separation(e0: vec2<f32>, e1: vec2<f32>, refp: vec2<f32>, box_corners: array<vec2<f32>,4>) -> bool \n"
    "{\n"
    "    let ref_dist = edge_distance(refp, e0, e1);\n"
    "\n"
    "    var all_opposite = true;\n"
    "    if (ref_dist > 0.0) \n"
    "    {\n"
    "        for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "        {\n"
    "            if (edge_distance(box_corners[i], e0, e1) >= 0.0) \n"
    "            {\n"
    "                all_opposite = false;\n"
    "            }\n"
    "        }\n"
    "    } else if (ref_dist < 0.0) \n"
    "    {\n"
    "        for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "        {\n"
    "            if (edge_distance(box_corners[i], e0, e1) <= 0.0) \n"
    "            {\n"
    "                all_opposite = false;\n"
    "            }\n"
    "        }\n"
    "    } else \n"
    "    {\n"
    "        all_opposite = false;\n"
    "    }\n"
    "\n"
    "    return all_opposite;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Intersection functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_ray(box: aabb, origin: vec2<f32>, direction: vec2<f32>) -> bool \n"
    "{\n"
    "    var tmin: f32 = 0.0;\n"
    "    var tmax: f32 = 1e10;\n"
    "\n"
    "    for (var i: u32 = 0; i < 2; i = i + 1) \n"
    "    {\n"
    "        let inv_dir = 1.0 / direction[i];\n"
    "        var t1 = (box.min[i] - origin[i]) * inv_dir;\n"
    "        var t2 = (box.max[i] - origin[i]) * inv_dir;\n"
    "\n"
    "        if (t1 > t2) \n"
    "        {\n"
    "            let temp = t1;\n"
    "            t1 = t2;\n"
    "            t2 = temp;\n"
    "        }\n"
    "\n"
    "        tmin = max(tmin, t1);\n"
    "        tmax = min(tmax, t2);\n"
    "\n"
    "        if (tmin > tmax) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_disc(box: aabb, center: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    let nearest_point = clamp(center, box.min, box.max);\n"
    "    return distance_squared(nearest_point, center) < square(radius);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_circle(box: aabb, center: vec2<f32>, radius: f32, half_width: f32) -> bool \n"
    "{\n"
    "    if (!intersection_aabb_disc(box, center, radius + half_width))\n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let candidate0 = abs(center - box.min);\n"
    "    let candidate1 = abs(center - box.max);\n"
    "    let furthest_point = max(candidate0, candidate1);\n"
    "\n"
    "    return length_squared(furthest_point) > square(radius - half_width);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_obb(box: aabb, p0: vec2<f32>, p1: vec2<f32>, width: f32) -> bool \n"
    "{\n"
    "    let dir = p1 - p0;\n"
    "    let center = (p0 + p1) * 0.5;\n"
    "    let height = length(dir);\n"
    "\n"
    "    let axis_j = dir / height;\n"
    "    let axis_i = vec2<f32>(-axis_j.y, axis_j.x);\n"
    "\n"
    "    let half_i = width * 0.5;\n"
    "    let half_j = height * 0.5;\n"
    "\n"
    "    let aabb_extent = abs(axis_i * half_i) + abs(axis_j * half_j);\n"
    "    let obb_min = center - aabb_extent;\n"
    "    let obb_max = center + aabb_extent;\n"
    "\n"
    "    if (all(obb_max < box.min) || all(box.max < obb_min)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let aabb_center = (box.min + box.max) * 0.5;\n"
    "    let aabb_half = (box.max - box.min) * 0.5;\n"
    "\n"
    "    var d = abs(dot(axis_i, center - aabb_center));\n"
    "    var r = aabb_half.x * abs(axis_i.x) + aabb_half.y * abs(axis_i.y);\n"
    "    if (d > (half_i + r)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    d = abs(dot(axis_j, center - aabb_center));\n"
    "    r = aabb_half.x * abs(axis_j.x) + aabb_half.y * abs(axis_j.y);\n"
    "    if (d > (half_j + r)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_triangle(box: aabb, p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>) -> bool \n"
    "{\n"
    "    let pmin = min(min(p0, p1), p2);\n"
    "    let pmax = max(max(p0, p1), p2);\n"
    "    if (any(pmax < box.min) || any(box.max < pmin)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    // Box corners\n"
    "    let v0 = box.min;\n"
    "    let v1 = box.max;\n"
    "    let v2 = vec2<f32>(box.min.x, box.max.y);\n"
    "    let v3 = vec2<f32>(box.max.x, box.min.y);\n"
    "    let box_corners: array<vec2<f32>,4> = array<vec2<f32>,4>(v0, v1, v2, v3);\n"
    "\n"
    "    // Edge separation tests\n"
    "    if (edge_separation(p0, p1, p2, box_corners)) { return false; }\n"
    "    if (edge_separation(p1, p2, p0, box_corners)) { return false; }\n"
    "    if (edge_separation(p2, p0, p1, box_corners)) { return false; }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_pie(box: aabb, center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    if (!intersection_aabb_disc(box, center, radius)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let center_vertex = normalize(aabb_vertices[i] - center);\n"
    "        if (dot(center_vertex, direction) > aperture.y) \n"
    "        {\n"
    "            return true;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return intersection_aabb_ray(box, center, direction);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_arc(box: aabb, center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32, thickness: f32) -> bool \n"
    "{\n"
    "    let half_thickness = thickness * 0.5;\n"
    "    if (!intersection_aabb_circle(box, center, radius, half_thickness)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "    return intersection_aabb_pie(box, center, direction, aperture, radius + half_thickness);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn point_in_triangle(p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>, point: vec2<f32>) -> bool \n"
    "{\n"
    "    let d1 = edge_distance(point, p0, p1);\n"
    "    let d2 = edge_distance(point, p1, p2);\n"
    "    let d3 = edge_distance(point, p2, p0);\n"
    "\n"
    "    let has_neg = (d1 < 0.0) || (d2 < 0.0) || (d3 < 0.0);\n"
    "    let has_pos = (d1 > 0.0) || (d2 > 0.0) || (d3 > 0.0);\n"
    "\n"
    "    return !(has_neg && has_pos);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn point_in_pie(center: vec2<f32>, direction: vec2<f32>, radius: f32, cos_aperture: f32, point: vec2<f32>) -> bool \n"
    "{\n"
    "    if (distance_squared(center, point) > square(radius)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "    let to_point = normalize(point - center);\n"
    "    return dot(to_point, direction) > cos_aperture;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_ellipse_circle(p0: vec2<f32>, p1: vec2<f32>, width: f32, center: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "    let transformed_center = obb_transform(obox, center) / obox.extents;\n"
    "    let scaled_radius = radius / min(obox.extents.x, obox.extents.y);\n"
    "    let squared_distance = dot(transformed_center, transformed_center);\n"
    "    return squared_distance <= square(1.0 + scaled_radius);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_ellipse(p0: vec2<f32>, p1: vec2<f32>, width: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let vertex_ellipse_space = obb_transform(obox, aabb_vertices[i]);\n"
    "        let distance = square(vertex_ellipse_space.x) / square(obox.extents.x) +\n"
    "                            square(vertex_ellipse_space.y) / square(obox.extents.y);\n"
    "        if (distance > 1.0) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_triangle(p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let d0 = edge_distance(p0, p1, aabb_vertices[i]);\n"
    "        let d1 = edge_distance(p1, p2, aabb_vertices[i]);\n"
    "        let d2 = edge_distance(p2, p0, aabb_vertices[i]);\n"
    "\n"
    "        let has_neg = (d0 < 0.0) || (d1 < 0.0) || (d2 < 0.0);\n"
    "        let has_pos = (d0 > 0.0) || (d1 > 0.0) || (d2 > 0.0);\n"
    "\n"
    "        if (has_neg && has_pos) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_obb(p0: vec2<f32>, p1: vec2<f32>, width: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let point = obb_transform(obox, aabb_vertices[i]);\n"
    "        if (any(abs(point) > obox.extents)) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_pie(center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>\n"
    "    (\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        if (!point_in_pie(center, direction, radius, aperture.y, aabb_vertices[i])) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Tile Binning Helpers\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn clip_tile(tile: aabb, clip: clip_rect) -> bool\n"
    "{\n"
    "    return (tile.max.x < clip.min_x || tile.max.y < clip.min_y || \n"
    "            tile.min.x > clip.max_x || tile.min.y > clip.max_y);\n"
    "}\n"
    "\n"
    "fn intersection_tile_command(tile_aabb: aabb, cmd: draw_command, aabb_margin: f32) -> bool\n"
    "{\n"
    "    let tile_enlarge_aabb = aabb_grow(tile_aabb, vec2<f32>(aabb_margin));\n"
    "    let is_hollow = (get_fillmode(cmd) == FILL_HOLLOW);\n"
    "    let cmd_type = get_type(cmd);\n"
    "    let data_idx = cmd.data_index;\n"
    "    var intersection = false;\n"
    "\n"
    "    switch (cmd_type)\n"
    "    {\n"
    "        case PRIMITIVE_ORIENTED_BOX:\n"
    "        {\n"
    "            let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "            let width = g_draw_data[data_idx + 4u];\n"
    "            let tile_rounded = aabb_grow(tile_enlarge_aabb, vec2<f32>(g_draw_data[data_idx + 5u]));\n"
    "            intersection = intersection_aabb_obb(tile_rounded, p0, p1, width);\n"
    "\n"
    "            if (intersection && is_hollow && is_aabb_inside_obb(p0, p1, width, tile_rounded))\n"
    "            {\n"
    "                intersection = false;\n"
    "            }\n"
    "        }\n"
    "        case PRIMITIVE_ELLIPSE:\n"
    "        {\n"
    "            let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "            let width = g_draw_data[data_idx + 4u];\n"
    "            let tile_center = (tile_aabb.min + tile_aabb.max) * 0.5;\n"
    "            let margin = select(0.0, g_draw_data[data_idx + 5u], is_hollow);\n"
    "            let tile_smooth = aabb_grow(tile_enlarge_aabb, vec2<f32>(margin));\n"
    "            intersection = intersection_ellipse_circle(p0, p1, width, tile_center, length(aabb_get_extents(tile_smooth) * 0.5));\n"
    "\n"
    "            if (intersection && is_hollow && is_aabb_inside_ellipse(p0, p1, width, tile_smooth))\n"
    "            {\n"
    "                intersection = false;\n"
    "            }\n"
    "        }\n"
    "        case PRIMITIVE_ARC:\n"
    "        {\n"
    "            let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let radius = g_draw_data[data_idx + 2u];\n"
    "            let direction = vec2<f32>(g_draw_data[data_idx + 3u], g_draw_data[data_idx + 4u]);\n"
    "            let aperture = vec2<f32>(g_draw_data[data_idx + 5u], g_draw_data[data_idx + 6u]);\n"
    "            let thickness = g_draw_data[data_idx + 7u];\n"
    "            intersection = intersection_aabb_arc(tile_enlarge_aabb, center, direction, aperture, radius, thickness);\n"
    "        }\n"
    "        case PRIMITIVE_PIE:\n"
    "        {\n"
    "            let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let radius = g_draw_data[data_idx + 2u];\n"
    "            let direction = vec2<f32>(g_draw_data[data_idx + 3u], g_draw_data[data_idx + 4u]);\n"
    "            let aperture = vec2<f32>(g_draw_data[data_idx + 5u], g_draw_data[data_idx + 6u]);\n"
    "            let margin = select(0.0, g_draw_data[data_idx + 7u], is_hollow);\n"
    "            let tile_smooth = aabb_grow(tile_enlarge_aabb, vec2<f32>(margin));\n"
    "            intersection = intersection_aabb_pie(tile_smooth, center, direction, aperture, radius);\n"
    "\n"
    "            if (intersection && is_hollow && is_aabb_inside_pie(center, direction, aperture, radius, tile_smooth))\n"
    "            {\n"
    "                intersection = false;\n"
    "            }\n"
    "        }\n"
    "        case PRIMITIVE_DISC:\n"
    "        {\n"
    "            let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            var radius = g_draw_data[data_idx + 2u];\n"
    "            if (is_hollow)\n"
    "            {\n"
    "                let half_width = g_draw_data[data_idx + 3u] + aabb_margin;\n"
    "                intersection = intersection_aabb_circle(tile_aabb, center, radius, half_width);\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                radius += aabb_margin;\n"
    "                intersection = intersection_aabb_disc(tile_aabb, center, radius);\n"
    "            }\n"
    "        }\n"
    "        case PRIMITIVE_TRIANGLE:\n"
    "        {\n"
    "            let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "            let p2 = vec2<f32>(g_draw_data[data_idx + 4u], g_draw_data[data_idx + 5u]);\n"
    "            let tile_rounded = aabb_grow(tile_enlarge_aabb, vec2<f32>(g_draw_data[data_idx + 6u]));\n"
    "            intersection = intersection_aabb_triangle(tile_rounded, p0, p1, p2);\n"
    "\n"
    "            if (intersection && is_hollow && is_aabb_inside_triangle(p0, p1, p2, tile_rounded))\n"
    "            {\n"
    "                intersection = false;\n"
    "            }\n"
    "        }\n"
    "        case PRIMITIVE_ORIENTED_QUAD:\n"
    "        {\n"
    "            let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "            let dimensions = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "            let axis = vec2<f32>(g_draw_data[data_idx + 4u], g_draw_data[data_idx + 5u]);\n"
    "            let dir = axis * .5f/dimensions.x;\n"
    "            let p0 = center + dir;\n"
    "            let p1 = center - dir;\n"
    "            intersection = intersection_aabb_obb(tile_aabb, p0, p1, 1.f/dimensions.y);\n"
    "        }\n"
    "        default:\n"
    "        {\n"
    "            intersection = true;\n"
    "        }\n"
    "    }\n"
    "    return intersection;\n"
    "}\n"
    "\n"
    "fn clean_list(tile_index: u32)\n"
    "{\n"
    "    var node_index: u32 = g_tile_heads[tile_index];\n"
    "    var previous_index: u32 = INVALID_INDEX;\n"
    "    var before_begin: u32 = INVALID_INDEX;\n"
    "    var num_primitives: u32 = 0u;\n"
    "\n"
    "    while (node_index != INVALID_INDEX)\n"
    "    {\n"
    "        let node = g_tile_nodes[node_index];\n"
    "        let cmd_idx = get_command_index(node);\n"
    "        let cmd = g_commands[cmd_idx];\n"
    "        let command_type = get_type(cmd);\n"
    "\n"
    "        if (command_type == BEGIN_GROUP)\n"
    "        {\n"
    "            before_begin = previous_index;\n"
    "            previous_index = node_index;\n"
    "            num_primitives = 0u;\n"
    "        }\n"
    "        else if (command_type == END_GROUP)\n"
    "        {\n"
    "            // no primitive between BEGIN_GROUP / END_GROUP\n"
    "            if (num_primitives == 0u)\n"
    "            {\n"
    "                // remove empty group pair from linked list\n"
    "                if (before_begin == INVALID_INDEX)\n"
    "                {\n"
    "                    g_tile_heads[tile_index] = node.next;\n"
    "                }\n"
    "                else\n"
    "                {\n"
    "                    g_tile_nodes[before_begin].next = node.next;\n"
    "                }\n"
    "\n"
    "                previous_index = before_begin;\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                previous_index = node_index;\n"
    "            }\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            num_primitives = num_primitives + 1u;\n"
    "            previous_index = node_index;\n"
    "        }\n"
    "\n"
    "        node_index = node.next;\n"
    "    }\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Compute Shaders\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "@compute @workgroup_size(16, 16, 1)\n"
    "fn tile_bin(@builtin(global_invocation_id) global_id: vec3<u32>)\n"
    "{\n"
    "    let tile_xy = global_id.xy;\n"
    "\n"
    "    if (tile_xy.x >= g_draw_args.num_tile_width || tile_xy.y >= g_draw_args.num_tile_height)\n"
    "    {\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    let tile_index:u32 = tile_xy.y * g_draw_args.num_tile_width + tile_xy.x;\n"
    "    \n"
    "    var current_head = INVALID_INDEX; \n"
    "\n"
    "    let tile_min = vec2<f32>(tile_xy) * TILE_SIZE;\n"
    "    let tile_max = (vec2<f32>(tile_xy) + 1.0) * TILE_SIZE;\n"
    "    let tile_aabb = aabb(tile_min, tile_max);\n"
    "\n"
    "    var aabb_margin: f32 = 0.0;\n"
    "\n"
    "    // REVERSE TRAVERSAL: Start from the last command and go to the first.\n"
    "    // This ensures that command 0 becomes the final 'head' of the linked list.\n"
    "    for (var i: i32 = i32(g_draw_args.num_commands) - 1; i >= 0; i--)\n"
    "    {\n"
    "        let cmd_idx = u32(i);\n"
    "        let cmd = g_commands[cmd_idx];\n"
    "        let cmd_type = get_type(cmd);\n"
    "\n"
    "        // coarse AABB check (quantized)\n"
    "        let q_aabb = g_quantized_aabb[cmd_idx];\n"
    "        let min_x = (q_aabb >> 0u) & 0xFFu;\n"
    "        let min_y = (q_aabb >> 8u) & 0xFFu;\n"
    "        let max_x = (q_aabb >> 16u) & 0xFFu;\n"
    "        let max_y = (q_aabb >> 24u) & 0xFFu;\n"
    "\n"
    "        if (tile_xy.x < min_x || tile_xy.y < min_y || tile_xy.x > max_x || tile_xy.y > max_y)\n"
    "        {\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        // clip Rect check\n"
    "        let clip_idx = get_clip(cmd);\n"
    "        let clip = g_clips[clip_idx];\n"
    "        if (clip_tile(tile_aabb, clip))\n"
    "        {\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        // fine-grained intersection test\n"
    "        let to_be_added = intersection_tile_command(tile_aabb, cmd, g_draw_args.aa_width + aabb_margin);\n"
    "\n"
    "        // we traverse in reverse order, so the end comes first\n"
    "        if (cmd_type == BEGIN_GROUP) \n"
    "        {\n"
    "            aabb_margin = 0.0;\n"
    "        }\n"
    "        else if (cmd_type == END_GROUP)\n"
    "        {\n"
    "            aabb_margin = g_draw_data[cmd.data_index];\n"
    "        }\n"
    "\n"
    "        if (to_be_added)\n"
    "        {\n"
    "            let node_idx = atomicAdd(&g_counters.num_nodes, 1u);\n"
    "\n"
    "            if (node_idx < g_draw_args.max_nodes)\n"
    "            {\n"
    "                let packed_info = (cmd_type << 16u) | (cmd_idx & 0xFFFFu);\n"
    "\n"
    "                g_tile_nodes[node_idx] = tile_node(current_head, packed_info);\n"
    "\n"
    "                current_head = node_idx;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    // Write final head to global buffer\n"
    "    g_tile_heads[tile_index] = current_head;\n"
    "\n"
    "    clean_list(tile_index);\n"
    "\n"
    "    // If tile is not empty, register it for processing\n"
    "    if (current_head != INVALID_INDEX)\n"
    "    {\n"
    "        let pos = atomicAdd(&g_counters.num_tiles, 1u);\n"
    "        g_tile_indices[pos] = tile_index;\n"
    "    }\n"
    "}\n"
    "\n"
    "@compute @workgroup_size(1, 1, 1)\n"
    "fn write_indirect_args()\n"
    "{\n"
    "    g_indirect_draw.vertex_count   = 4u;\n"
    "    g_indirect_draw.instance_count = atomicLoad(&g_counters.num_tiles);\n"
    "    g_indirect_draw.first_vertex   = 0u;\n"
    "    g_indirect_draw.first_instance = 0u;\n"
    "}\n"
;

#endif // __binning_shader__H__
