#ifndef __binning_shader__H__
#define __binning_shader__H__

#include <stddef.h>

static const size_t binning_shader_size = 14914;
static const char binning_shader[] =
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Common structures and bindgroups\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct draw_command \n"
    "{\n"
    "    data_index : u32,\n"
    "    flags      : u32 // extra (8) | clip_index (8) | fillmode (8) | type (8)\n"
    "};\n"
    "\n"
    "fn get_extra(cmd: draw_command) -> u32  {return cmd.flags & 0xFFu;}\n"
    "fn get_clip(cmd: draw_command) -> u32 {return (cmd.flags >> 8u) & 0xFFu;}\n"
    "fn get_fillmode(cmd: draw_command) -> u32 {return (cmd.flags >> 16u) & 0xFFu;}\n"
    "fn get_type(cmd: draw_command) -> u32 {return (cmd.flags >> 24u) & 0xFFu;}\n"
    "\n"
    "struct tile_node\n"
    "{\n"
    "    next          : u32,\n"
    "    command_index : u32 // command index + command type\n"
    "};\n"
    "\n"
    "fn get_command_index(n : tile_node) -> u32 {return n.command_index & 0xFFFFu;}\n"
    "fn get_command_type(n : tile_node) -> u32 {return (n.command_index >> 16u) & 0xFFu;}\n"
    "\n"
    "struct counters\n"
    "{\n"
    "    num_nodes : atomic<u32>,\n"
    "    num_tiles : atomic<u32>\n"
    "};\n"
    "\n"
    "struct draw_args \n"
    "{\n"
    "    num_commands: u32,\n"
    "    num_tile_width: u32,\n"
    "    num_tile_height: u32,\n"
    "    max_nodes: u32,\n"
    "    screen_div: vec2<f32>,\n"
    "    aa_width: f32\n"
    "};\n"
    "\n"
    "struct glyph\n"
    "{\n"
    "    uv_topleft : vec2<f32>,\n"
    "    uv_bottomright : vec2<f32>,\n"
    "    width : f32,\n"
    "    height : f32\n"
    "};\n"
    "\n"
    "struct clip_rect\n"
    "{\n"
    "    min_x : f32,\n"
    "    min_y : f32,\n"
    "    max_x : f32,\n"
    "    max_y : f32\n"
    "};\n"
    "\n"
    "// group 0 : static or updated on gpu\n"
    "@group(0) @binding(0)\n"
    "var<storage, read_write> g_tile_nodes : array<tile_node>;\n"
    "\n"
    "@group(0) @binding(1)\n"
    "var<storage, read_write> g_tile_indices : array<u32>;\n"
    "\n"
    "@group(0) @binding(2)\n"
    "var<storage, read_write> g_counters : counters;\n"
    "\n"
    "@group(0) @binding(3)\n"
    "var<storage, read_write> g_glyphs : array<glyph>;\n"
    "\n"
    "// group 1 : updated each frame\n"
    "@group(1) @binding(0)\n"
    "var<uniform> g_draw_args: draw_args;\n"
    "\n"
    "@group(1) @binding(1)\n"
    "var<storage, read> g_commands : array<draw_command>;\n"
    "\n"
    "@group(1) @binding(2)\n"
    "var<storage, read> g_quantized_aabb : array<u32>;\n"
    "\n"
    "@group(1) @binding(3)\n"
    "var<storage> g_draw_data: array<f32>;\n"
    "\n"
    "@group(1) @binding(4)\n"
    "var<storage> g_clips: array<clip_rect>;\n"
    "\n"
    "@group(1) @binding(5)\n"
    "var<storage> g_colors: array<u32>;\n"
    "\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Constants\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "const TILE_SIZE: f32 = 16.0;\n"
    "\n"
    "\n"
    "\n"
    "struct aabb\n"
    "{\n"
    "    min : vec2<f32>,\n"
    "    max : vec2<f32>\n"
    "};\n"
    "\n"
    "struct obb\n"
    "{\n"
    "    axis_i : vec2<f32>,\n"
    "    axis_j : vec2<f32>,\n"
    "    center : vec2<f32>,\n"
    "    extents : vec2<f32>\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Helpers\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn skew(v: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    return vec2<f32>(-v.y, v.x);\n"
    "}\n"
    "\n"
    "fn distance_squared(a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    let d = a - b;\n"
    "    return dot(d, d);\n"
    "}\n"
    "\n"
    "fn length_squared(v: vec2<f32>) -> f32 \n"
    "{\n"
    "    return dot(v, v);\n"
    "}\n"
    "\n"
    "fn square(x: f32) -> f32 \n"
    "{\n"
    "    return x * x;\n"
    "}\n"
    "\n"
    "fn aabb_grow(box: aabb, amount: vec2<f32>) -> aabb \n"
    "{\n"
    "    return aabb(box.min - amount, box.max + amount);\n"
    "}\n"
    "\n"
    "fn aabb_get_extents(box: aabb) -> vec2<f32> {return box.max - box.min;}\n"
    "\n"
    "fn compute_obb(p0: vec2<f32>, p1: vec2<f32>, width: f32) -> obb \n"
    "{\n"
    "    var result: obb;\n"
    "\n"
    "    result.center = (p0 + p1) * 0.5;\n"
    "    result.axis_j = p1 - result.center;\n"
    "    result.extents.y = length(result.axis_j);\n"
    "    result.axis_j = result.axis_j / result.extents.y;\n"
    "    result.axis_i = skew(result.axis_j);\n"
    "    result.extents.x = width * 0.5;\n"
    "\n"
    "    return result;\n"
    "}\n"
    "\n"
    "fn obb_transform(obox: obb, point: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    let p = point - obox.center;\n"
    "    return vec2<f32>(\n"
    "        abs(dot(obox.axis_i, p)),\n"
    "        abs(dot(obox.axis_j, p))\n"
    "    );\n"
    "}\n"
    "\n"
    "fn edge_distance(p: vec2<f32>, a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    return (b.y - a.y) * (p.x - a.x) - (b.x - a.x) * (p.y - a.y);\n"
    "}\n"
    "\n"
    "fn edge_separation(e0: vec2<f32>, e1: vec2<f32>, refp: vec2<f32>, box_corners: array<vec2<f32>,4>) -> bool \n"
    "{\n"
    "    let ref_dist = edge_distance(refp, e0, e1);\n"
    "\n"
    "    var all_opposite = true;\n"
    "    if (ref_dist > 0.0) \n"
    "    {\n"
    "        for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "        {\n"
    "            if (edge_distance(box_corners[i], e0, e1) >= 0.0) \n"
    "            {\n"
    "                all_opposite = false;\n"
    "            }\n"
    "        }\n"
    "    } else if (ref_dist < 0.0) \n"
    "    {\n"
    "        for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "        {\n"
    "            if (edge_distance(box_corners[i], e0, e1) <= 0.0) \n"
    "            {\n"
    "                all_opposite = false;\n"
    "            }\n"
    "        }\n"
    "    } else \n"
    "    {\n"
    "        all_opposite = false;\n"
    "    }\n"
    "\n"
    "    return all_opposite;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Intersection functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_ray(box: aabb, origin: vec2<f32>, direction: vec2<f32>) -> bool \n"
    "{\n"
    "    var tmin: f32 = 0.0;\n"
    "    var tmax: f32 = 1e10;\n"
    "\n"
    "    for (var i: u32 = 0; i < 2; i = i + 1) \n"
    "    {\n"
    "        let inv_dir = 1.0 / direction[i];\n"
    "        var t1 = (box.min[i] - origin[i]) * inv_dir;\n"
    "        var t2 = (box.max[i] - origin[i]) * inv_dir;\n"
    "\n"
    "        if (t1 > t2) \n"
    "        {\n"
    "            let temp = t1;\n"
    "            t1 = t2;\n"
    "            t2 = temp;\n"
    "        }\n"
    "\n"
    "        tmin = max(tmin, t1);\n"
    "        tmax = min(tmax, t2);\n"
    "\n"
    "        if (tmin > tmax) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_disc(box: aabb, center: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    let nearest_point = clamp(center, box.min, box.max);\n"
    "    return distance_squared(nearest_point, center) < square(radius);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_circle(box: aabb, center: vec2<f32>, radius: f32, half_width: f32) -> bool \n"
    "{\n"
    "    if (!intersection_aabb_disc(box, center, radius + half_width))\n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let candidate0 = abs(center - box.min);\n"
    "    let candidate1 = abs(center - box.max);\n"
    "    let furthest_point = max(candidate0, candidate1);\n"
    "\n"
    "    return length_squared(furthest_point) > square(radius - half_width);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_obb(box: aabb, p0: vec2<f32>, p1: vec2<f32>, width: f32) -> bool \n"
    "{\n"
    "    let dir = p1 - p0;\n"
    "    let center = (p0 + p1) * 0.5;\n"
    "    let height = length(dir);\n"
    "\n"
    "    let axis_j = dir / height;\n"
    "    let axis_i = vec2<f32>(-axis_j.y, axis_j.x);\n"
    "\n"
    "    let half_i = width * 0.5;\n"
    "    let half_j = height * 0.5;\n"
    "\n"
    "    let aabb_extent = abs(axis_i * half_i) + abs(axis_j * half_j);\n"
    "    let obb_min = center - aabb_extent;\n"
    "    let obb_max = center + aabb_extent;\n"
    "\n"
    "    if (all(obb_max < box.min) || all(box.max < obb_min)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let aabb_center = (box.min + box.max) * 0.5;\n"
    "    let aabb_half = (box.max - box.min) * 0.5;\n"
    "\n"
    "    var d = abs(dot(axis_i, center - aabb_center));\n"
    "    var r = aabb_half.x * abs(axis_i.x) + aabb_half.y * abs(axis_i.y);\n"
    "    if (d > (half_i + r)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    d = abs(dot(axis_j, center - aabb_center));\n"
    "    r = aabb_half.x * abs(axis_j.x) + aabb_half.y * abs(axis_j.y);\n"
    "    if (d > (half_j + r)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_triangle(box: aabb, p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>) -> bool \n"
    "{\n"
    "    let pmin = min(min(p0, p1), p2);\n"
    "    let pmax = max(max(p0, p1), p2);\n"
    "    if (any(pmax < box.min) || any(box.max < pmin)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    // Box corners\n"
    "    let v0 = box.min;\n"
    "    let v1 = box.max;\n"
    "    let v2 = vec2<f32>(box.min.x, box.max.y);\n"
    "    let v3 = vec2<f32>(box.max.x, box.min.y);\n"
    "    let box_corners: array<vec2<f32>,4> = array<vec2<f32>,4>(v0, v1, v2, v3);\n"
    "\n"
    "    // Edge separation tests\n"
    "    if (edge_separation(p0, p1, p2, box_corners)) { return false; }\n"
    "    if (edge_separation(p1, p2, p0, box_corners)) { return false; }\n"
    "    if (edge_separation(p2, p0, p1, box_corners)) { return false; }\n"
    "\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_pie(box: aabb, center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    if (!intersection_aabb_disc(box, center, radius)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let center_vertex = normalize(aabb_vertices[i] - center);\n"
    "        if (dot(center_vertex, direction) > aperture.y) \n"
    "        {\n"
    "            return true;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return intersection_aabb_ray(box, center, direction);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_aabb_arc(box: aabb, center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32, thickness: f32) -> bool \n"
    "{\n"
    "    let half_thickness = thickness * 0.5;\n"
    "    if (!intersection_aabb_circle(box, center, radius, half_thickness)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "    return intersection_aabb_pie(box, center, direction, aperture, radius + half_thickness);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn point_in_triangle(p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>, point: vec2<f32>) -> bool \n"
    "{\n"
    "    let d1 = edge_distance(point, p0, p1);\n"
    "    let d2 = edge_distance(point, p1, p2);\n"
    "    let d3 = edge_distance(point, p2, p0);\n"
    "\n"
    "    let has_neg = (d1 < 0.0) || (d2 < 0.0) || (d3 < 0.0);\n"
    "    let has_pos = (d1 > 0.0) || (d2 > 0.0) || (d3 > 0.0);\n"
    "\n"
    "    return !(has_neg && has_pos);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn point_in_pie(center: vec2<f32>, direction: vec2<f32>, radius: f32, cos_aperture: f32, point: vec2<f32>) -> bool \n"
    "{\n"
    "    if (distance_squared(center, point) > square(radius)) \n"
    "    {\n"
    "        return false;\n"
    "    }\n"
    "    let to_point = normalize(point - center);\n"
    "    return dot(to_point, direction) > cos_aperture;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn intersection_ellipse_circle(p0: vec2<f32>, p1: vec2<f32>, width: f32, center: vec2<f32>, radius: f32) -> bool \n"
    "{\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "    let transformed_center = obb_transform(obox, center) / obox.extents;\n"
    "    let scaled_radius = radius / min(obox.extents.x, obox.extents.y);\n"
    "    let squared_distance = dot(transformed_center, transformed_center);\n"
    "    return squared_distance <= square(1.0 + scaled_radius);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_ellipse(p0: vec2<f32>, p1: vec2<f32>, width: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let vertex_ellipse_space = obb_transform(obox, aabb_vertices[i]);\n"
    "        let distance = square(vertex_ellipse_space.x) / square(obox.extents.x) +\n"
    "                            square(vertex_ellipse_space.y) / square(obox.extents.y);\n"
    "        if (distance > 1.0) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_triangle(p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let d0 = edge_distance(p0, p1, aabb_vertices[i]);\n"
    "        let d1 = edge_distance(p1, p2, aabb_vertices[i]);\n"
    "        let d2 = edge_distance(p2, p0, aabb_vertices[i]);\n"
    "\n"
    "        let has_neg = (d0 < 0.0) || (d1 < 0.0) || (d2 < 0.0);\n"
    "        let has_pos = (d0 > 0.0) || (d1 > 0.0) || (d2 > 0.0);\n"
    "\n"
    "        if (has_neg && has_pos) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_obb(p0: vec2<f32>, p1: vec2<f32>, width: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>(\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    let obox = compute_obb(p0, p1, width);\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        let point = obb_transform(obox, aabb_vertices[i]);\n"
    "        if (any(abs(point) > obox.extents)) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "fn is_aabb_inside_pie(center: vec2<f32>, direction: vec2<f32>, aperture: vec2<f32>, radius: f32, box: aabb) -> bool \n"
    "{\n"
    "    let aabb_vertices: array<vec2<f32>, 4> = array<vec2<f32>, 4>\n"
    "    (\n"
    "        box.min,\n"
    "        box.max,\n"
    "        vec2<f32>(box.min.x, box.max.y),\n"
    "        vec2<f32>(box.max.x, box.min.y)\n"
    "    );\n"
    "\n"
    "    for (var i: u32 = 0; i < 4; i = i + 1) \n"
    "    {\n"
    "        if (!point_in_pie(center, direction, radius, aperture.y, aabb_vertices[i])) \n"
    "        {\n"
    "            return false;\n"
    "        }\n"
    "    }\n"
    "    return true;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Tile binning\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "\n"
    "\n"
    "\n"
;

#endif // __binning_shader__H__
