#ifndef __rasterizer_shader__H__
#define __rasterizer_shader__H__

#include <stddef.h>

static const size_t rasterizer_shader_size = 6649;
static const char rasterizer_shader[] =
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Common structures and bindgroups\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct draw_command \n"
    "{\n"
    "    data_index : u32,\n"
    "    flags      : u32 // extra (8) | clip_index (8) | fillmode (8) | type (8)\n"
    "};\n"
    "\n"
    "fn get_extra(cmd: draw_command) -> u32  {return cmd.flags & 0xFFu;}\n"
    "fn get_clip(cmd: draw_command) -> u32 {return (cmd.flags >> 8u) & 0xFFu;}\n"
    "fn get_fillmode(cmd: draw_command) -> u32 {return (cmd.flags >> 16u) & 0xFFu;}\n"
    "fn get_type(cmd: draw_command) -> u32 {return (cmd.flags >> 24u) & 0xFFu;}\n"
    "\n"
    "struct tile_node\n"
    "{\n"
    "    next          : u32,\n"
    "    command_index : u32 // command index + command type\n"
    "};\n"
    "\n"
    "fn get_command_index(n : tile_node) -> u32 {return n.command_index & 0xFFFFu;}\n"
    "fn get_command_type(n : tile_node) -> u32 {return (n.command_index >> 16u) & 0xFFu;}\n"
    "\n"
    "struct counters\n"
    "{\n"
    "    num_nodes : atomic<u32>,\n"
    "    num_tiles : atomic<u32>\n"
    "};\n"
    "\n"
    "struct draw_args \n"
    "{\n"
    "    num_commands: u32,\n"
    "    num_tile_width: u32,\n"
    "    num_tile_height: u32,\n"
    "    max_nodes: u32,\n"
    "    screen_div: vec2<f32>,\n"
    "    aa_width: f32\n"
    "};\n"
    "\n"
    "struct glyph\n"
    "{\n"
    "    uv_topleft : vec2<f32>,\n"
    "    uv_bottomright : vec2<f32>,\n"
    "    width : f32,\n"
    "    height : f32\n"
    "};\n"
    "\n"
    "struct clip_rect\n"
    "{\n"
    "    min_x : f32,\n"
    "    min_y : f32,\n"
    "    max_x : f32,\n"
    "    max_y : f32\n"
    "};\n"
    "\n"
    "// group 0 : static or updated on gpu\n"
    "@group(0) @binding(0)\n"
    "var<storage, read_write> g_tile_nodes : array<tile_node>;\n"
    "\n"
    "@group(0) @binding(1)\n"
    "var<storage, read_write> g_tile_indices : array<u32>;\n"
    "\n"
    "@group(0) @binding(2)\n"
    "var<storage, read_write> g_counters : counters;\n"
    "\n"
    "@group(0) @binding(3)\n"
    "var<storage, read_write> g_glyphs : array<glyph>;\n"
    "\n"
    "// group 1 : updated each frame\n"
    "@group(1) @binding(0)\n"
    "var<uniform> g_draw_args: draw_args;\n"
    "\n"
    "@group(1) @binding(1)\n"
    "var<storage, read> g_commands : array<draw_command>;\n"
    "\n"
    "@group(1) @binding(2)\n"
    "var<storage, read> g_quantized_aabb : array<u32>;\n"
    "\n"
    "@group(1) @binding(3)\n"
    "var<storage> g_draw_data: array<f32>;\n"
    "\n"
    "@group(1) @binding(4)\n"
    "var<storage> g_clip: array<clip_rect>;\n"
    "\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Constants\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "const TILE_SIZE: f32 = 16.0;\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Helpers\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn saturate(x: f32) -> f32 \n"
    "{\n"
    "    return clamp(x, 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn linearstep(edge0: f32, edge1: f32, x: f32) -> f32 \n"
    "{\n"
    "    return clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn skew(v: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    return vec2<f32>(-v.y, v.x);\n"
    "}\n"
    "\n"
    "fn linear_to_srgb_channel(c: f32) -> f32 \n"
    "{\n"
    "    if (c <= 0.0031308) \n"
    "    {\n"
    "        return c * 12.92;\n"
    "    }\n"
    "    return 1.055 * pow(c, 1.0 / 2.4) - 0.055;\n"
    "}\n"
    "\n"
    "fn linear_to_srgb(color: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    return vec4<f32>\n"
    "    (\n"
    "        linear_to_srgb_channel(color.r),\n"
    "        linear_to_srgb_channel(color.g),\n"
    "        linear_to_srgb_channel(color.b),\n"
    "        color.a\n"
    "    );\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Signed distance functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn erf_approx(x: f32) -> f32 \n"
    "{\n"
    "    return sign(x) * sqrt(1.0 - exp2(-1.787776 * x * x));\n"
    "}\n"
    "\n"
    "fn sd_disc(position: vec2<f32>, center: vec2<f32>, radius: f32) -> f32 \n"
    "{\n"
    "    return length(center - position) - radius;\n"
    "}\n"
    "\n"
    "fn sd_aabox(position: vec2<f32>, box_center: vec2<f32>, half_extents: vec2<f32>, radius: f32) -> f32 \n"
    "{\n"
    "    var p = abs(position - box_center) - half_extents + vec2<f32>(radius);\n"
    "    return length(max(p, vec2<f32>(0.0))) +\n"
    "           min(max(p.x, p.y), 0.0) - radius;\n"
    "}\n"
    "\n"
    "fn sd_oriented_box(position: vec2<f32>, a: vec2<f32>, b: vec2<f32>, width: f32) -> f32 \n"
    "{\n"
    "    let l = length(b - a);\n"
    "    let d = (b - a) / l;\n"
    "    var q = position - (a + b) * 0.5;\n"
    "\n"
    "    let rot = mat2x2<f32>(d.x, -d.y, d.y,  d.x);\n"
    "\n"
    "    q = rot * q;\n"
    "    q = abs(q) - vec2<f32>(l, width) * 0.5;\n"
    "\n"
    "    return length(max(q, vec2<f32>(0.0))) + min(max(q.x, q.y), 0.0);\n"
    "}\n"
    "\n"
    "fn sd_segment(p: vec2<f32>, a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    let pa = p - a;\n"
    "    let ba = b - a;\n"
    "    let h = saturate(dot(pa, ba) / dot(ba, ba));\n"
    "    return length(pa - ba * h);\n"
    "}\n"
    "\n"
    "fn smooth_minimum(a_in: f32, b_in: f32, k: f32) -> vec2<f32> \n"
    "{\n"
    "    var a = a_in;\n"
    "    var b = max(b_in, 0.0);\n"
    "\n"
    "    if (k > 0.0) \n"
    "    {\n"
    "        let h = max(k - abs(a - b), 0.0) / k;\n"
    "        let m = h * h * h * 0.5;\n"
    "        let s = m * k * (1.0 / 3.0);\n"
    "\n"
    "        if (a < b) \n"
    "        {\n"
    "            return vec2<f32>(a - s, 0.0);\n"
    "        } \n"
    "        else \n"
    "        {\n"
    "            return vec2<f32>(b - s, 1.0 - linearstep(-k, 0.0, b - a));\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return vec2<f32>(min(a, b), select(1.0, 0.0, a < b));\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Vertex shader\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct vs_out \n"
    "{\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) @interpolate(flat) tile_index: u32\n"
    "};\n"
    "\n"
    "@vertex\n"
    "fn tile_vs(@builtin(instance_index) instance_id: u32, @builtin(vertex_index) vertex_id: u32) -> vs_out\n"
    "{\n"
    "    var out: vs_out;\n"
    "\n"
    "    let tile_index = g_tile_indices[instance_id];\n"
    "    let tile_x = tile_index % g_draw_args.num_tile_width;\n"
    "    let tile_y = tile_index / g_draw_args.num_tile_width;\n"
    "\n"
    "    var screen_pos = vec2<f32>(f32(vertex_id & 1u), f32(vertex_id >> 1u));\n"
    "\n"
    "    screen_pos += vec2<f32>(f32(tile_x), f32(tile_y));\n"
    "    screen_pos *= TILE_SIZE;\n"
    "\n"
    "    var clipspace = screen_pos * g_draw_args.screen_div;\n"
    "    clipspace = clipspace * 2.0 - vec2<f32>(1.0);\n"
    "    clipspace.y = -clipspace.y;\n"
    "\n"
    "    out.pos = vec4<f32>(clipspace, 0.0, 1.0);\n"
    "    out.tile_index = tile_index;\n"
    "\n"
    "    return out;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Fragment shader\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "@fragment\n"
    "fn tile_fs(in: vs_out) -> @location(0) vec4<f32> \n"
    "{\n"
    "\n"
    "    var output = vec4<f32>(0.0);\n"
    "\n"
    "    return output;\n"
    "}\n"
;

#endif // __rasterizer_shader__H__
