#ifndef __rasterizer_shader__H__
#define __rasterizer_shader__H__

#include <stddef.h>

static const size_t rasterizer_shader_size = 27098;
static const char rasterizer_shader[] =
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Structures\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct draw_command \n"
    "{\n"
    "    data_index : u32,\n"
    "    flags      : u32 // extra (8) | clip_index (8) | fillmode (8) | type (8)\n"
    "};\n"
    "\n"
    "struct tile_node\n"
    "{\n"
    "    next          : u32,\n"
    "    command_index : u32 // command index + command type\n"
    "};\n"
    "\n"
    "struct counters\n"
    "{\n"
    "    num_nodes : atomic<u32>,\n"
    "    num_tiles : atomic<u32>\n"
    "};\n"
    "\n"
    "struct draw_args \n"
    "{\n"
    "    clear_color: vec4<f32>,\n"
    "    screen_div: vec2<f32>,\n"
    "    num_commands: u32,\n"
    "    num_tile_width: u32,\n"
    "    num_tile_height: u32,\n"
    "    max_nodes: u32,\n"
    "    aa_width: f32,\n"
    "    options: u32,\n"
    "};\n"
    "\n"
    "struct glyph\n"
    "{\n"
    "    uv_topleft : vec2<f32>,\n"
    "    uv_bottomright : vec2<f32>,\n"
    "    width : f32,\n"
    "    height : f32\n"
    "};\n"
    "\n"
    "struct clip_rect\n"
    "{\n"
    "    min_x : f32,\n"
    "    min_y : f32,\n"
    "    max_x : f32,\n"
    "    max_y : f32\n"
    "};\n"
    "\n"
    "struct aabb\n"
    "{\n"
    "    min : vec2<f32>,\n"
    "    max : vec2<f32>\n"
    "};\n"
    "\n"
    "struct obb\n"
    "{\n"
    "    axis_i : vec2<f32>,\n"
    "    axis_j : vec2<f32>,\n"
    "    center : vec2<f32>,\n"
    "    extents : vec2<f32>\n"
    "}\n"
    "\n"
    "struct indirect_params \n"
    "{\n"
    "    vertex_count: u32,\n"
    "    instance_count: u32,\n"
    "    first_vertex: u32,\n"
    "    first_instance: u32\n"
    "};\n"
    "\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn get_extra(cmd: draw_command) -> u32  {return cmd.flags & 0xFFu;}\n"
    "fn get_clip(cmd: draw_command) -> u32 {return (cmd.flags >> 8u) & 0xFFu;}\n"
    "fn get_fillmode(cmd: draw_command) -> u32 {return (cmd.flags >> 16u) & 0xFFu;}\n"
    "fn get_type(cmd: draw_command) -> u32 {return (cmd.flags >> 24u) & 0xFFu;}\n"
    "fn get_command_index(n : tile_node) -> u32 {return n.command_index & 0xFFFFu;}\n"
    "fn get_command_type(n : tile_node) -> u32 {return (n.command_index >> 16u) & 0xFFu;}\n"
    "\n"
    "\n"
    "/*\n"
    "\n"
    "//-----------------------------------------------------------------------------\n"
    "// based on https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-23-high-speed-screen-particles\n"
    "// we also use a specific blend equation\n"
    "half4 accumulate_color(half4 color, half4 backbuffer)\n"
    "{\n"
    "    half4 output;\n"
    "    output.rgb = (color.rgb * color.a) + (backbuffer.rgb * (1.f - color.a));\n"
    "    output.a = backbuffer.a * (1.f - color.a);\n"
    "    return output;\n"
    "}\n"
    "\n"
    "*/\n"
    "\n"
    "fn accumulate_color(color: vec4<f32>, backbuffer: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    let rgb = mix(backbuffer.rgb, color.rgb, color.a);\n"
    "    return vec4<f32>(rgb, 1.0);\n"
    "}\n"
    "\n"
    "fn linear_to_srgb_channel(c: f32) -> f32 \n"
    "{\n"
    "    if (c <= 0.0031308) \n"
    "    {\n"
    "        return c * 12.92;\n"
    "    } else \n"
    "    {\n"
    "        return 1.055 * pow(c, 1.0 / 2.4) - 0.055;\n"
    "    }\n"
    "}\n"
    "\n"
    "fn linear_to_srgb(linear_color: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    return vec4<f32>(\n"
    "        linear_to_srgb_channel(linear_color.r),\n"
    "        linear_to_srgb_channel(linear_color.g),\n"
    "        linear_to_srgb_channel(linear_color.b),\n"
    "        linear_color.a\n"
    "    );\n"
    "}\n"
    "\n"
    "fn srgb_to_linear(srgb: vec4<f32>) -> vec4<f32> \n"
    "{\n"
    "    let rgb = srgb.rgb;\n"
    "    let linear_rgb = select(\n"
    "        pow((rgb + 0.055) / 1.055, vec3<f32>(2.4)),\n"
    "        rgb / 12.92,\n"
    "        rgb <= vec3<f32>(0.04045)\n"
    "    );\n"
    "    return vec4<f32>(linear_rgb, srgb.a);\n"
    "}\n"
    "\n"
    "fn saturate(x: f32) -> f32 \n"
    "{\n"
    "    return clamp(x, 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn linearstep(edge0: f32, edge1: f32, x: f32) -> f32 \n"
    "{\n"
    "    return clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "fn skew(v: vec2<f32>) -> vec2<f32> \n"
    "{\n"
    "    return vec2<f32>(-v.y, v.x);\n"
    "}\n"
    "\n"
    "fn distance_squared(a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    let d = a - b;\n"
    "    return dot(d, d);\n"
    "}\n"
    "\n"
    "fn length_squared(v: vec2<f32>) -> f32 \n"
    "{\n"
    "    return dot(v, v);\n"
    "}\n"
    "\n"
    "fn square(x: f32) -> f32 \n"
    "{\n"
    "    return x * x;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Constants\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "const TILE_SIZE: f32 = 16.0;\n"
    "const PRIMITIVE_CHAR: u32 = 0u;\n"
    "const PRIMITIVE_AABOX: u32 = 1u;\n"
    "const PRIMITIVE_ORIENTED_BOX: u32 = 2u;\n"
    "const PRIMITIVE_DISC: u32 = 3u;\n"
    "const PRIMITIVE_TRIANGLE: u32 = 4u;\n"
    "const PRIMITIVE_ELLIPSE: u32 = 5u;\n"
    "const PRIMITIVE_PIE: u32 = 6u;\n"
    "const PRIMITIVE_ARC: u32 = 7u;\n"
    "const PRIMITIVE_BLURRED_BOX: u32 = 8u;\n"
    "const PRIMITIVE_QUAD: u32 = 9u;\n"
    "const PRIMITIVE_ORIENTED_QUAD: u32 = 10u;\n"
    "const BEGIN_GROUP: u32 = 32u;\n"
    "const END_GROUP: u32 = 33u;\n"
    "const INVALID_INDEX:u32 = 0xFFFFFFFFu;\n"
    "const OP_UNION:u32 = 0u;\n"
    "const OP_SUBTRACTION:u32 = 1u;\n"
    "const OP_INTERSECTION:u32 = 2u;\n"
    "const FILL_SOLID:u32 = 0u;\n"
    "const FILL_OUTLINE:u32 = 1u;\n"
    "const FILL_HOLLOW:u32 = 2u;\n"
    "const FILL_GRADIENT:u32 = 3u;\n"
    "const OPTION_SRGB_BACKBUFFER:u32 = (1u<<0);\n"
    "const OPTION_DEBUG_BINNING:u32 = (1u<<1);\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Bindgroups\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "// group 0 : static or updated on gpu\n"
    "@group(0) @binding(0)\n"
    "var<storage, read> g_tile_nodes : array<tile_node>;\n"
    "\n"
    "@group(0) @binding(1)\n"
    "var<storage, read> g_tile_indices : array<u32>;\n"
    "\n"
    "@group(0) @binding(2)\n"
    "var<storage, read> g_glyphs : array<glyph>;\n"
    "\n"
    "@group(0) @binding(3)\n"
    "var<storage, read> g_tile_heads : array<u32>;\n"
    "\n"
    "@group(0) @binding(4) \n"
    "var g_atlas: texture_2d_array<f32>;\n"
    "\n"
    "@group(0) @binding(5) \n"
    "var g_atlas_sampler: sampler;\n"
    "\n"
    "@group(0) @binding(6) \n"
    "var g_font: texture_2d<f32>;\n"
    "\n"
    "@group(0) @binding(7) \n"
    "var g_font_sampler: sampler;\n"
    "\n"
    "// group 1 : updated each frame\n"
    "@group(1) @binding(0)\n"
    "var<storage, read> g_draw_args: draw_args;\n"
    "\n"
    "@group(1) @binding(1)\n"
    "var<storage, read> g_commands : array<draw_command>;\n"
    "\n"
    "@group(1) @binding(2)\n"
    "var<storage, read> g_quantized_aabb : array<u32>;\n"
    "\n"
    "@group(1) @binding(3)\n"
    "var<storage, read> g_draw_data: array<f32>;\n"
    "\n"
    "@group(1) @binding(4)\n"
    "var<storage, read> g_clips: array<clip_rect>;\n"
    "\n"
    "@group(1) @binding(5)\n"
    "var<storage, read> g_colors: array<u32>;\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Signed distance functions\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "fn op_union(lhs: f32, rhs: f32, aa_width : f32) -> vec2<f32> \n"
    "{\n"
    "    // previous color is always overwritten by new one in case of overlap\n"
    "    var a = rhs;\n"
    "    var b = max(lhs, 0.0);\n"
    "\n"
    "    if (a<b)\n"
    "    {\n"
    "        return vec2<f32>(a, 0.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        return vec2<f32>(b, 1.0 - linearstep(-aa_width, 0.0, b-a));\n"
    "    }\n"
    "}\n"
    "\n"
    "fn op_subtraction(lhs: f32, rhs: f32) -> f32\n"
    "{\n"
    "    return max(-rhs, lhs);\n"
    "}\n"
    "\n"
    "fn op_intersection(lhs: f32, rhs: f32) -> f32\n"
    "{\n"
    "    return max(lhs, rhs);\n"
    "}\n"
    "\n"
    "fn erf_approx(x: f32) -> f32 \n"
    "{\n"
    "    return sign(x) * sqrt(1.0 - exp2(-1.787776 * x * x));\n"
    "}\n"
    "\n"
    "fn sd_disc(position: vec2<f32>, center: vec2<f32>, radius: f32) -> f32 \n"
    "{\n"
    "    return length(center - position) - radius;\n"
    "}\n"
    "\n"
    "fn sd_aabox(position: vec2<f32>, box_center: vec2<f32>, half_extents: vec2<f32>, radius: f32) -> f32 \n"
    "{\n"
    "    var p = abs(position - box_center) - half_extents + vec2<f32>(radius);\n"
    "    return length(max(p, vec2<f32>(0.0))) +\n"
    "           min(max(p.x, p.y), 0.0) - radius;\n"
    "}\n"
    "\n"
    "fn sd_oriented_box(position: vec2<f32>, a: vec2<f32>, b: vec2<f32>, width: f32) -> f32 \n"
    "{\n"
    "    let l = length(b - a);\n"
    "    let d = (b - a) / l;\n"
    "    var q = position - (a + b) * 0.5;\n"
    "\n"
    "    let rot = mat2x2<f32>(d.x, -d.y, d.y,  d.x);\n"
    "\n"
    "    q = rot * q;\n"
    "    q = abs(q) - vec2<f32>(l, width) * 0.5;\n"
    "\n"
    "    return length(max(q, vec2<f32>(0.0))) + min(max(q.x, q.y), 0.0);\n"
    "}\n"
    "\n"
    "fn sd_segment(p: vec2<f32>, a: vec2<f32>, b: vec2<f32>) -> f32 \n"
    "{\n"
    "    let pa = p - a;\n"
    "    let ba = b - a;\n"
    "    let h = saturate(dot(pa, ba) / dot(ba, ba));\n"
    "    return length(pa - ba * h);\n"
    "}\n"
    "\n"
    "fn sd_triangle(p: vec2<f32>, p0: vec2<f32>, p1: vec2<f32>, p2: vec2<f32>) -> f32 \n"
    "{\n"
    "    let e0 = p1 - p0;\n"
    "    let e1 = p2 - p1;\n"
    "    let e2 = p0 - p2;\n"
    "\n"
    "    let v0 = p - p0;\n"
    "    let v1 = p - p1;\n"
    "    let v2 = p - p2;\n"
    "\n"
    "    let pq0 = v0 - e0 * saturate(dot(v0, e0) / dot(e0, e0));\n"
    "    let pq1 = v1 - e1 * saturate(dot(v1, e1) / dot(e1, e1));\n"
    "    let pq2 = v2 - e2 * saturate(dot(v2, e2) / dot(e2, e2));\n"
    "    \n"
    "    let s = e0.x * e2.y - e0.y * e2.x;\n"
    "    \n"
    "    let d = min(min(vec2<f32>(dot(pq0, pq0), s * (v0.x * e0.y - v0.y * e0.x)),\n"
    "                    vec2<f32>(dot(pq1, pq1), s * (v1.x * e1.y - v1.y * e1.x))),\n"
    "                    vec2<f32>(dot(pq2, pq2), s * (v2.x * e2.y - v2.y * e2.x)));\n"
    "\n"
    "    return -sqrt(d.x) * sign(d.y);\n"
    "}\n"
    "\n"
    "fn sd_gaussian_box(position_in: vec2<f32>, box_center: vec2<f32>, box_size: vec2<f32>, radius: f32) -> vec2<f32> \n"
    "{\n"
    "    let p = position_in - box_center;\n"
    "    let d = abs(p) - box_size;\n"
    "    let sd = length(max(d, vec2<f32>(0.0))) + min(max(d.x, d.y), 0.0) - radius;\n"
    "    \n"
    "    let blur_radius = radius * 0.5;\n"
    "\n"
    "    let u = erf_approx((p.x + box_size.x) / blur_radius) - erf_approx((p.x - box_size.x) / blur_radius);\n"
    "    let v = erf_approx((p.y + box_size.y) / blur_radius) - erf_approx((p.y - box_size.y) / blur_radius);\n"
    "    \n"
    "    return vec2<f32>(sd, u * v / 4.0);\n"
    "}\n"
    "\n"
    "fn sd_ellipse(p: vec2<f32>, e: vec2<f32>) -> f32 \n"
    "{\n"
    "    let pAbs = abs(p);\n"
    "    let ei = 1.0 / e;\n"
    "    let e2 = e * e;\n"
    "    let ve = ei * vec2<f32>(e2.x - e2.y, e2.y - e2.x);\n"
    "    \n"
    "    var t = vec2<f32>(0.70710678118, 0.70710678118);\n"
    "\n"
    "    // Iterative refinement to find the nearest point on the ellipse\n"
    "    for (var i: i32 = 0; i < 3; i++) \n"
    "    {\n"
    "        let v = ve * t * t * t;\n"
    "        let u = normalize(pAbs - v) * length(t * e - v);\n"
    "        let w = ei * (v + u);\n"
    "        t = normalize(clamp(w, vec2<f32>(0.0), vec2<f32>(1.0)));\n"
    "    }\n"
    "    \n"
    "    let nearestAbs = t * e;\n"
    "    let dist = length(pAbs - nearestAbs);\n"
    "    return select(dist, -dist, dot(pAbs, pAbs) < dot(nearestAbs, nearestAbs));\n"
    "}\n"
    "\n"
    "fn sd_oriented_ellipse(position: vec2<f32>, a: vec2<f32>, b: vec2<f32>, width: f32) -> f32 \n"
    "{\n"
    "    let height = length(b - a);\n"
    "    let axis = (b - a) / height;\n"
    "    let pos_translated = position - (a + b) * 0.5;\n"
    "\n"
    "    let rot = mat2x2<f32>(vec2<f32>(axis.x, axis.y),vec2<f32>(-axis.y, axis.x));\n"
    "    let pos_boxspace = pos_translated * rot;\n"
    "\n"
    "    return sd_ellipse(pos_boxspace, vec2<f32>(height * 0.5, width * 0.5));\n"
    "}\n"
    "\n"
    "fn sd_oriented_pie(position_in: vec2<f32>, center: vec2<f32>, direction_in: vec2<f32>, aperture: vec2<f32>, radius: f32) -> f32 \n"
    "{\n"
    "    let dir = -skew(direction_in);\n"
    "    let p_rel = position_in - center;\n"
    "    \n"
    "    let rot = mat2x2<f32>(vec2<f32>(dir.x, dir.y),vec2<f32>(-dir.y, dir.x));\n"
    "    let p = p_rel * rot;\n"
    "    \n"
    "    let px_abs = abs(p.x);\n"
    "    let l = length(p) - radius;\n"
    "    let m = length(vec2<f32>(px_abs, p.y) - aperture * clamp(dot(vec2<f32>(px_abs, p.y), aperture), 0.0, radius));\n"
    "    return max(l, m * sign(aperture.y * px_abs - aperture.x * p.y));\n"
    "}\n"
    "\n"
    "fn sd_oriented_arc(position_in: vec2<f32>, center: vec2<f32>, direction_in: vec2<f32>, aperture: vec2<f32>, radius: f32, thickness: f32) -> f32 \n"
    "{\n"
    "    let dir = -skew(direction_in);\n"
    "    var p_rel = position_in - center;\n"
    "    let rot = mat2x2<f32>(vec2<f32>(dir.x, dir.y),vec2<f32>(-dir.y, dir.x));\n"
    "    var p = p_rel * rot;\n"
    "\n"
    "    p.x = abs(p.x);\n"
    "    \n"
    "    // Rotate by aperture matrix\n"
    "    p = vec2<f32>(-aperture.y * p.x - aperture.x * p.y,aperture.x * p.x - aperture.y * p.y);\n"
    "    \n"
    "    let half_thick = thickness * 0.5;\n"
    "    let d1 = abs(length(p) - radius) - half_thick;\n"
    "    let d2 = length(vec2<f32>(p.x, max(0.0, abs(radius - p.y) - half_thick))) * sign(p.x);\n"
    "    \n"
    "    return max(d1, d2);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Vertex shader\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "struct vs_out \n"
    "{\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) @interpolate(flat) tile_index: u32\n"
    "};\n"
    "\n"
    "@vertex\n"
    "fn tile_vs(@builtin(instance_index) instance_id: u32, @builtin(vertex_index) vertex_id: u32) -> vs_out\n"
    "{\n"
    "    var out: vs_out;\n"
    "\n"
    "    let tile_index = g_tile_indices[instance_id];\n"
    "    let tile_x = tile_index % g_draw_args.num_tile_width;\n"
    "    let tile_y = tile_index / g_draw_args.num_tile_width;\n"
    "\n"
    "    var screen_pos = vec2<f32>(f32(vertex_id & 1u), f32(vertex_id >> 1u));\n"
    "\n"
    "    screen_pos += vec2<f32>(f32(tile_x), f32(tile_y));\n"
    "    screen_pos *= TILE_SIZE;\n"
    "\n"
    "    var clipspace = screen_pos * g_draw_args.screen_div;\n"
    "    clipspace = clipspace * 2.0 - vec2<f32>(1.0);\n"
    "    clipspace.y = -clipspace.y;\n"
    "\n"
    "    out.pos = vec4<f32>(clipspace, 0.0, 1.0);\n"
    "    out.tile_index = tile_index;\n"
    "\n"
    "    return out;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "// Fragment shader\n"
    "// ---------------------------------------------------------------------------------------------------------------------------\n"
    "\n"
    "@fragment\n"
    "fn tile_fs(in: vs_out) -> @location(0) vec4<f32> \n"
    "{\n"
    "    var output:vec4<f32> = g_draw_args.clear_color;\n"
    "\n"
    "    if ((g_draw_args.options & OPTION_DEBUG_BINNING) != 0u)\n"
    "    {\n"
    "        output = vec4<f32>(0.0, 0.0, 1.0, 1.0);\n"
    "    }\n"
    " \n"
    "    var node_idx:u32 = g_tile_heads[in.tile_index];\n"
    "    if (node_idx == INVALID_INDEX)\n"
    "    {\n"
    "        return output;\n"
    "    }\n"
    "\n"
    "    var previous_distance: f32 = 1e8;\n"
    "    var previous_color: vec4<f32> = vec4<f32>(0.0);\n"
    "    var group_op: u32 = OP_UNION;\n"
    "    var grouping: bool = false;\n"
    "    var group_first_primitive: bool = false;\n"
    "    var outline_width: f32 = 0.0;\n"
    "\n"
    "    while (node_idx != INVALID_INDEX)\n"
    "    {\n"
    "        let node = g_tile_nodes[node_idx];\n"
    "        let cmd_idx = get_command_index(node);\n"
    "        let cmd = g_commands[cmd_idx];\n"
    "        \n"
    "        // extract info using your helpers\n"
    "        let cmd_type = get_type(cmd);\n"
    "        let fillmode = get_fillmode(cmd);\n"
    "        let extra    = get_extra(cmd);\n"
    "        let clip_idx = get_clip(cmd);\n"
    "        let data_idx = cmd.data_index;\n"
    "        let clip       = g_clips[clip_idx];\n"
    "\n"
    "        var cmd_color: vec4<f32> = srgb_to_linear(unpack4x8unorm(g_colors[cmd_idx]));\n"
    "\n"
    "        let clipped = (in.pos.x < clip.min_x || in.pos.y < clip.min_y || \n"
    "                       in.pos.x > clip.max_x || in.pos.y > clip.max_y);\n"
    "\n"
    "        if (!clipped)\n"
    "        {\n"
    "            var distance: f32 = 10.0;\n"
    "\n"
    "            if (cmd_type == BEGIN_GROUP)\n"
    "            {\n"
    "                previous_color = vec4<f32>(0.0);\n"
    "                previous_distance = 1e8;\n"
    "                grouping = true;\n"
    "                group_first_primitive = true;\n"
    "                group_op = extra;\n"
    "                outline_width = g_draw_data[data_idx];\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "                switch (cmd_type)\n"
    "                {\n"
    "                    case PRIMITIVE_DISC:\n"
    "                    {\n"
    "                        let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let radius = g_draw_data[data_idx + 2u];\n"
    "                        distance = sd_disc(in.pos.xy, center, radius);\n"
    "                        \n"
    "                        if (fillmode == FILL_HOLLOW) \n"
    "                        {\n"
    "                            distance = abs(distance) - g_draw_data[data_idx + 3u];\n"
    "                        } \n"
    "                        else if (fillmode == FILL_GRADIENT) \n"
    "                        {\n"
    "                            let packed_color = bitcast<u32>(g_draw_data[data_idx + 3u]);\n"
    "                            let inner_color = srgb_to_linear(unpack4x8unorm(packed_color));\n"
    "                            cmd_color = mix(inner_color, cmd_color, linearstep(-radius, 0.0, distance));\n"
    "                        }\n"
    "                    }\n"
    "                    case PRIMITIVE_ORIENTED_BOX:\n"
    "                    {\n"
    "                        let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let width = g_draw_data[data_idx + 4u];\n"
    "\n"
    "                        if (width == 0.0) \n"
    "                        {\n"
    "                            distance = sd_segment(in.pos.xy, p0, p1);\n"
    "                        } else \n"
    "                        {\n"
    "                            distance = sd_oriented_box(in.pos.xy, p0, p1, width);\n"
    "                        }\n"
    "\n"
    "                        if (fillmode == FILL_HOLLOW) \n"
    "                        {\n"
    "                            distance = abs(distance);\n"
    "                        } \n"
    "                        else if (fillmode == FILL_GRADIENT) \n"
    "                        {\n"
    "                            let packed_color = bitcast<u32>(g_draw_data[data_idx + 6u]);\n"
    "                            let inner_color = srgb_to_linear(unpack4x8unorm(packed_color));\n"
    "                            let pa = in.pos.xy - p0;\n"
    "                            let ba = p1 - p0;\n"
    "                            let h = saturate(dot(pa, ba) / dot(ba, ba));\n"
    "                            cmd_color = mix(inner_color, cmd_color, h);\n"
    "                        }\n"
    "                        distance -= g_draw_data[data_idx + 5u];\n"
    "                    }\n"
    "                    case PRIMITIVE_ELLIPSE:\n"
    "                    {\n"
    "                        let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let width = g_draw_data[data_idx + 4u];\n"
    "\n"
    "                        distance = sd_oriented_ellipse(in.pos.xy, p0, p1, width);\n"
    "\n"
    "                        if (fillmode == FILL_HOLLOW) \n"
    "                        {\n"
    "                            distance = abs(distance) - g_draw_data[data_idx + 5u];;\n"
    "                        }\n"
    "                    }\n"
    "                    case PRIMITIVE_AABOX:\n"
    "                    {\n"
    "                        let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let half_ext = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        distance = sd_aabox(in.pos.xy, center, half_ext, g_draw_data[data_idx + 4u]);\n"
    "                    }\n"
    "                    case PRIMITIVE_TRIANGLE: \n"
    "                    {\n"
    "                        let p0 = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let p1 = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let p2 = vec2<f32>(g_draw_data[data_idx + 4u], g_draw_data[data_idx + 5u]);\n"
    "                        distance = sd_triangle(in.pos.xy, p0, p1, p2);\n"
    "                        \n"
    "                        if (fillmode == FILL_HOLLOW) \n"
    "                        {\n"
    "                            distance = abs(distance);\n"
    "                        }\n"
    "                        distance -= g_draw_data[data_idx + 6u];\n"
    "                    }\n"
    "                    case PRIMITIVE_BLURRED_BOX: \n"
    "                    {\n"
    "                        let center = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let size   = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let roundness = g_draw_data[data_idx + 4u];\n"
    "                        \n"
    "                        let res = sd_gaussian_box(in.pos.xy, center, size, roundness);\n"
    "                        distance = res.x;\n"
    "                        cmd_color.a *= res.y; // apply the gaussian alpha\n"
    "                    }\n"
    "                    case PRIMITIVE_CHAR: \n"
    "                    {\n"
    "                        let glyph_idx = extra;\n"
    "                        let top_left = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let g = g_glyphs[glyph_idx];\n"
    "                        let t = (in.pos.xy - top_left) / vec2<f32>(g.width, g.height);\n"
    "                        if (all(t >= vec2<f32>(0.0)) && all(t <= vec2<f32>(1.0))) \n"
    "                        {\n"
    "                            distance = (1.0 - textureSample(g_font, g_font_sampler, mix(g.uv_topleft, g.uv_bottomright, t)).r) * g_draw_args.aa_width;\n"
    "                        }\n"
    "                    }\n"
    "                    case PRIMITIVE_QUAD: \n"
    "                    {\n"
    "                        let top_left     = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let bottom_right = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let uv_topleft   = vec2<f32>(g_draw_data[data_idx + 4u], g_draw_data[data_idx + 5u]);\n"
    "                        let uv_bottomright = vec2<f32>(g_draw_data[data_idx + 6u], g_draw_data[data_idx + 7u]);\n"
    "                        \n"
    "                        // Calculate normalized local coordinates (0.0 to 1.0)\n"
    "                        let t = (in.pos.xy - top_left) / (bottom_right - top_left);\n"
    "\n"
    "                        if (all(t >= vec2<f32>(0.0)) && all(t <= vec2<f32>(1.0))) \n"
    "                        {\n"
    "                            let uv = mix(uv_topleft, uv_bottomright, t);\n"
    "                            let tex_color = textureSample(g_atlas, g_atlas_sampler, uv, i32(extra));\n"
    "                            cmd_color = cmd_color * tex_color;\n"
    "                            distance = 0.0;\n"
    "                        }\n"
    "                    }\n"
    "                    case PRIMITIVE_ORIENTED_QUAD: \n"
    "                    {\n"
    "                        let center       = vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let dimensions   = vec2<f32>(g_draw_data[data_idx + 2u], g_draw_data[data_idx + 3u]);\n"
    "                        let axis         = vec2<f32>(g_draw_data[data_idx + 4u], g_draw_data[data_idx + 5u]);\n"
    "                        let uv_topleft   = vec2<f32>(g_draw_data[data_idx + 6u], g_draw_data[data_idx + 7u]);\n"
    "                        let uv_bottomright = vec2<f32>(g_draw_data[data_idx + 8u], g_draw_data[data_idx + 9u]);\n"
    "\n"
    "                        let relative = in.pos.xy - center;\n"
    "                        \n"
    "                        var t = vec2<f32>(dot(axis, relative), dot(skew(axis), relative));\n"
    "                        \n"
    "                        t = t * dimensions + 0.5;\n"
    "\n"
    "                        if (all(t >= vec2<f32>(0.0)) && all(t <= vec2<f32>(1.0)))\n"
    "                        {\n"
    "                            let uv = mix(uv_topleft, uv_bottomright, t);\n"
    "                            let tex_color = textureSample(g_atlas, g_atlas_sampler, uv, i32(extra));\n"
    "                            cmd_color = cmd_color * tex_color;\n"
    "                            distance = 0.0;\n"
    "                        }\n"
    "                    }\n"
    "                    case PRIMITIVE_ARC:\n"
    "                    {\n"
    "                        let center= vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let radius = g_draw_data[data_idx + 2u];\n"
    "                        let direction= vec2<f32>(g_draw_data[data_idx + 3u], g_draw_data[data_idx + 4u]);\n"
    "                        let aperture= vec2<f32>(g_draw_data[data_idx + 5u], g_draw_data[data_idx + 6u]);\n"
    "                        let thickness = g_draw_data[data_idx + 7u];\n"
    "                        distance = sd_oriented_arc(in.pos.xy, center, direction, aperture, radius, thickness);\n"
    "                    }\n"
    "                    case PRIMITIVE_PIE:\n"
    "                    {\n"
    "                        let center= vec2<f32>(g_draw_data[data_idx + 0u], g_draw_data[data_idx + 1u]);\n"
    "                        let radius = g_draw_data[data_idx + 2u];\n"
    "                        let direction= vec2<f32>(g_draw_data[data_idx + 3u], g_draw_data[data_idx + 4u]);\n"
    "                        let aperture= vec2<f32>(g_draw_data[data_idx + 5u], g_draw_data[data_idx + 6u]);\n"
    "                        distance = sd_oriented_pie(in.pos.xy, center, direction, aperture, radius);\n"
    "\n"
    "                        if (fillmode == FILL_HOLLOW) \n"
    "                        {\n"
    "                            distance = abs(distance) - g_draw_data[data_idx + 7u];\n"
    "                        }\n"
    "                    }\n"
    "                    default: { distance = 1e8; }\n"
    "                }\n"
    "\n"
    "                var final_color: vec4<f32>;\n"
    "                if (cmd_type == END_GROUP)\n"
    "                {\n"
    "                    grouping = false;\n"
    "                    final_color = previous_color;\n"
    "                    distance = previous_distance;\n"
    "                }\n"
    "                else\n"
    "                {\n"
    "                    final_color = cmd_color;\n"
    "                }\n"
    "\n"
    "                if (grouping)\n"
    "                {\n"
    "                    // first primitive in the group just set the initial distance/color\n"
    "                    if (group_first_primitive)\n"
    "                    {\n"
    "                        previous_distance = distance;\n"
    "                        previous_color = final_color;\n"
    "                        group_first_primitive = false;\n"
    "                    }\n"
    "                    else\n"
    "                    {\n"
    "                        switch(group_op)\n"
    "                        {\n"
    "                            case OP_UNION:\n"
    "                            {\n"
    "                                let res = op_union(previous_distance, distance, g_draw_args.aa_width);\n"
    "                                previous_distance = res.x;\n"
    "                                previous_color = mix(final_color, previous_color, res.y);\n"
    "                            }\n"
    "                            case OP_SUBTRACTION:\n"
    "                            {\n"
    "                                previous_distance = op_subtraction(previous_distance, distance);\n"
    "                            }\n"
    "                            case OP_INTERSECTION:\n"
    "                            {\n"
    "                                previous_distance = op_intersection(previous_distance, distance);\n"
    "                            }\n"
    "                            default: {previous_distance = 1e8;}\n"
    "                        }\n"
    "                    }\n"
    "                }\n"
    "                else\n"
    "                {\n"
    "                    var alpha_factor: f32;\n"
    "                    if (outline_width > 0.0 && cmd_type == END_GROUP)\n"
    "                    {\n"
    "                        if (distance > g_draw_args.aa_width) \n"
    "                        {\n"
    "                            final_color = vec4<f32>(cmd_color.rgb, final_color.a); \n"
    "                        } \n"
    "                        else \n"
    "                        {\n"
    "                            final_color = vec4<f32>(mix(cmd_color.rgb, final_color.rgb, linearstep(g_draw_args.aa_width, 0.0, distance)), final_color.a);\n"
    "                        }\n"
    "                        alpha_factor = linearstep(g_draw_args.aa_width * 2.0 + outline_width, g_draw_args.aa_width + outline_width, distance);\n"
    "                        outline_width = 0.0;\n"
    "                    }\n"
    "                    else\n"
    "                    {\n"
    "                        alpha_factor = linearstep(g_draw_args.aa_width, 0.0, distance);\n"
    "                    }\n"
    "\n"
    "                    final_color.a *= alpha_factor;\n"
    "                    output = accumulate_color(final_color, output);\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "        node_idx = node.next;\n"
    "    }\n"
    "\n"
    "    if ((g_draw_args.options & OPTION_SRGB_BACKBUFFER) == 0u)\n"
    "    {\n"
    "        output = linear_to_srgb(output);\n"
    "    }\n"
    "\n"
    "    return output;\n"
    "}\n"
;

#endif // __rasterizer_shader__H__
